on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: build android apk and app bundle, and linux .deb package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          version: 1.0
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: cp .env.sample .env
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart pub global activate flutter_distributor
      # - run: flutter test
      - run: export PATH="$PATH":"$HOME/.pub-cache/bin" && flutter_distributor package --platform android --targets=apk,aab
      - name: Upload Android Build Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          path: dist/*/polify-*-android.*
      - run: flutter config --enable-linux-desktop
      - run: export PATH="$PATH":"$HOME/.pub-cache/bin" && flutter_distributor package --platform linux --targets deb
      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: dist/*/polify-*-linux.deb
