on:
  push:
    tags:
      - "*"

jobs:
  build-linux:
    name: build linux desktop app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: cp .env.sample .env
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build linux --release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: polify_linux
          path: build/linux/x64/release
  build-android:
    name: build android apk and app bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: cp .env.sample .env
      - run: dart run build_runner build --delete-conflicting-outputs
      # - run: flutter test
      - run: flutter build apk
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: polify.apk
          path: build/app/outputs/apk/release/app-release.apk
      - run: flutter build appbundle
